### ISSUE TITLE
Can't use the gradle built jar in my own project

### ISSUE THREAD

**Issue by Yengas** [Netflix/sstable-adaptor#4]
Hello,

I have tried to build this project with `gradle shadowJar` and use it in my own project. However, even though i can access the classes in the project, i get an error while i try to read a SSTable. To make sure that the problem wasn't with the SSTable or my code, i wrote the same code in `sstable-adaptor` projects test code, and it works without a problem, i can read my sstable data in the [test case](https://github.com/Netflix/sstable-adaptor/blob/4c038602cb4c9e104abdceb17fcc6a4cf07b3fad/sstable-adaptor-core/src/test/java/com/netflix/sstableadaptor/TestSStableDataLister.java#L139).

However when i try the same code on my own project with the built  jar, i get an error:
```
log4j:WARN No appenders could be found for logger (org.apache.hadoop.util.Shell).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.io.IOException: No FileSystem for scheme: file
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:172)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:357)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at org.apache.cassandra.io.util.ChannelProxy.getInstance(ChannelProxy.java:79)
	at org.apache.cassandra.io.util.ChannelProxy.getInstance(ChannelProxy.java:71)
	at org.apache.cassandra.io.util.RandomAccessReader.open(RandomAccessReader.java:315)
	at org.apache.cassandra.io.sstable.metadata.MetadataSerializer.deserialize(MetadataSerializer.java:100)
	at com.netflix.sstableadaptor.util.SSTableUtils.metadataFromSSTable(SSTableUtils.java:316)
	at com.netflix.sstableadaptor.sstable.SSTableSingleReader.initialization(SSTableSingleReader.java:168)
	at com.netflix.sstableadaptor.sstable.SSTableSingleReader.<init>(SSTableSingleReader.java:141)
	at com.netflix.sstableadaptor.sstable.SSTableSingleReader.<init>(SSTableSingleReader.java:120)
	at com.netflix.sstableadaptor.sstable.SSTableSingleReader.<init>(SSTableSingleReader.java:77)
	at Main.main(Main.java:6)
Exception in thread "main" java.lang.NullPointerException
	at org.apache.cassandra.io.util.RandomAccessReader.open(RandomAccessReader.java:324)
	at org.apache.cassandra.io.sstable.metadata.MetadataSerializer.deserialize(MetadataSerializer.java:100)
	at com.netflix.sstableadaptor.util.SSTableUtils.metadataFromSSTable(SSTableUtils.java:316)
	at com.netflix.sstableadaptor.sstable.SSTableSingleReader.initialization(SSTableSingleReader.java:168)
	at com.netflix.sstableadaptor.sstable.SSTableSingleReader.<init>(SSTableSingleReader.java:141)
	at com.netflix.sstableadaptor.sstable.SSTableSingleReader.<init>(SSTableSingleReader.java:120)
	at com.netflix.sstableadaptor.sstable.SSTableSingleReader.<init>(SSTableSingleReader.java:77)
	at Main.main(Main.java:6)
```

this is my code:

```
SSTableSingleReader reader = new SSTableSingleReader("/home/yengas/Workspace/sstable-transform-data/node-0/data_points/mc-133-big-Data.db");
ISSTableScanner scanner = reader.getSSTableScanner(Long.MIN_VALUE, Long.MAX_VALUE);

while(scanner.hasNext()){
    while(scanner.hasNext()){
        System.out.println(scanner.next().partitionKey().getKey());
    }
}
```

Any idea why i am getting the NullPointerException?

**Comment by Yengas** [comment]
It works when i create a Gradle project, add the `./gradlew build`'s jars as a Gradle dependency, and add all of the compile dependencies from `sstable-adaptor-cassandra` & `sstable-adaptor-core` projects into my own `build.gradle`. This is something wrong with the `shadowJar`?

**Comment by timiblossom** [comment]
I thought this is still a private project for now and not sure how you can still see it.  We will plan to open source it soon.  

About your issue, it looks like there is some dependency collision to cause shadow jar not to work and if you plan to use this, you need to work around that or probably help us to fix it.  For us, internally, we just pull the raw jar of this to use, not the shadow jar.
